export const API_DEVELOPER = "api::developer.developer"
export const API_PUBLISHER = "api::publisher.publisher"
export const API_GAME = "api::game.game"
export const API_CATEGORY = "api::category.category"
export const API_PLATFORM = "api::platform.platform"
